//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PandaHotelWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoHabitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoHabitacion()
        {
            this.ReservaDetalle = new HashSet<ReservaDetalle>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public double precioTipoHab { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaDetalle> ReservaDetalle { get; set; }
    }
}
