//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Reserva_Alquiler_Habi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public int Id { get; set; }
        public string descripcion { get; set; }
        public int categoria { get; set; }
        public Nullable<int> piso { get; set; }
        public Nullable<int> habilitado { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
        public virtual Piso Piso1 { get; set; }
    }
}
