//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Reserva_Alquiler_Habi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitacion()
        {
            this.AlquilerDetalle = new HashSet<AlquilerDetalle>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> categoria { get; set; }
        public Nullable<int> piso { get; set; }
        public Nullable<int> habilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlquilerDetalle> AlquilerDetalle { get; set; }
        public virtual Categoria Categoria1 { get; set; }
        public virtual Piso Piso1 { get; set; }
    }
}
