//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Reserva_Alquiler_Habi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaDetalle
    {
        public int Id { get; set; }
        public int tipoHabitacion { get; set; }
        public Nullable<int> categoria { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> reserva_id { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
        public virtual Reserva Reserva { get; set; }
        public virtual TipoHabitacion TipoHabitacion1 { get; set; }
    }
}
